name: .NET CI & Quality Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    # 1. Controleer Code Formatting
    - name: Check Code Formatting (dotnet format)
      run: dotnet format --verify-no-changes --verbosity diagnostic

    # 2. Build & Code Quality Analyse (Compiler & Roslyn Analyzers)
    - name: Build & Analyze Code Quality
      run: dotnet build --no-restore -c Release

    # 3. Voer Tests uit
    - name: Run Tests
      run: dotnet test --no-build -c Release --verbosity normal


    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal