name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]


jobs:
  resolve:
    if: github.event.label.name == 'fix-me'
    uses: All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@main
    with:
      macro_model_name: "gemini/gemini-3.5-flash-lite" # optional: specify your free LLM model
    secrets:
      llm_api_key: ${{ secrets.LLM_API_KEY }}
      github_token: ${{ secrets.GITHUB_TOKEN }}